### ISSUE TITLE
Settings window makes the style of Anki Change on macOS

### ISSUE THREAD

**Issue by sandersantema** [sth2018/FastWordQuery#48]
**Describe the bug**
Settings window makes the style of Anki Change, for a better explanation see the screenshots below. It isn't a really big problem, Anki even seems to work faster with the non native window look. Although it might be better to fix this. 

**To Reproduce**
1. Go to the settings window
2. Done

**Screenshots**
How it normally looks:
<img width="1280" alt="schermafbeelding 2018-08-30 om 22 14 21" src="https://user-images.githubusercontent.com/21057514/44913467-c250aa00-ad2d-11e8-92e7-d9d19abdaea4.png">
How it looks after opening the fast word query settings window:
<img width="1280" alt="schermafbeelding 2018-08-30 om 22 12 22" src="https://user-images.githubusercontent.com/21057514/44913483-cbda1200-ad2d-11e8-8fa3-4e0e24bbdeb4.png">

**Comment by sth2018** [comment]
I knew about this problem. This bug is only in macOS, it's for fixing a bug which the close button is not visible on macOS.
If using the default style, the close button would be invisible. 
Using Fusion style the close button was OK, but the style of Anki also changed. 
This bug is caused by Pyqt. If Anki updates the Pyqt someday & fixed this bug, I'll remove changing style code of Anki, it will be back normal.

**Comment by sandersantema** [comment]
Could you tell me how I can enable Anki to always run in fusion mode? Because it seems to run faster that way.

**Comment by OshinoLichy** [comment]
My Anki works smoother due to this issue (
